jibri: add posibility to use SIP Video Gateway in JiBRI refactoring builder script logic moved to mod/Dockerfile

diff --git a/jibri/rootfs/etc/cont-init.d/10-config b/jibri/rootfs/etc/cont-init.d/10-config
--- a/jibri/rootfs/etc/cont-init.d/10-config
+++ b/jibri/rootfs/etc/cont-init.d/10-config
@@ -6,25 +6,31 @@ if [[ ! -z ${JIBRI_EXTERNAL_INSTANCE} ]]; then
   echo "${DOCKER_HOST_ADDRESS}  ${XMPP_SERVER}" >> /etc/hosts
 fi
 
-# DISPLAY is necessary for start
-[ -z "${DISPLAY}" ] \
-&& ( echo -e "\e[31mERROR: Please set DISPLAY variable.\e[39m"; kill 1; exit 1 )
-
 # check loaded snd_aloop module and exit if is not loaded on the host
 [ -z "$(lsmod |grep -om1 snd_aloop)" ] \
 && ( echo -e "\e[31mERROR: Please load snd-aloop module on the docker host.\e[39m"; kill 1; exit 1 )
 
-# get host's audio group id
+# get host's audio/video group id
 host_audio_group="$(stat -c %g /dev/snd/pcmC0D0p 2>/dev/null)"
+host_video_group="$(stat -c %g /dev/video10 2>/dev/null)"
 
-# audio group is not found. Has it been run without jibri.yml?
+# audio/video group is not found. Has it been run without jibri.yml?
 [ -z "${host_audio_group}" ] \
 && ( echo -e "\e[31mERROR: Binding /dev/snd is not found. Please check that you run docker-compose with -f jibri.yml.\e[39m"; kill 1; exit 1 )
 
+[ -z "${host_video_group}" ] \
+&& ( echo -e "\e[31mERROR: Binding /dev/video10 is not found. Please check that you run docker-compose with -f jibri.yml.\e[39m"; kill 1; exit 1 )
+
+# add video group
+groupadd jibri-video >/dev/null 2>&1
+
 # try to create group with this id. If group with the id already exists, just skip
 groupadd -g ${host_audio_group} jibri-audio >/dev/null 2>&1
-# include user to the group by id
+groupadd -g ${host_video_group} jibri-video >/dev/null 2>&1
+
+# include user to the groups by id
 usermod -aG ${host_audio_group} jibri
+usermod -aG ${host_video_group} jibri
 
 # script for finalizing must have executing bit.
 if [ ! -z "${JIBRI_FINALIZE_RECORDING_SCRIPT_PATH}" ];then
@@ -43,6 +49,22 @@ fi
 # always recreate configs
 tpl /defaults/config.json > /etc/jitsi/jibri/config.json
 tpl /defaults/logging.properties > /etc/jitsi/jibri/logging.properties
+tpl /defaults/asoundrc > /home/jibri/.asoundrc
+tpl /defaults/pjsua.config > /etc/jitsi/jibri/pjsua.config
+tpl /defaults/pjsua.sh > /opt/jitsi/jibri/pjsua.sh
+
+# replace /usr/bin/google-chrome link for extend functionality before start browser google-chrome
+rm -f /usr/bin/google-chrome \
+&& tpl /defaults/google-chrome.replace > /usr/bin/google-chrome \
+&& chmod +x /usr/bin/google-chrome
+
+# configure X params for screen 1
+sed 's/Virtual 1280 720/Virtual 1920 1080/' /etc/jitsi/jibri/xorg-video-dummy.conf > /etc/jitsi/jibri/xorg-display0.conf \
+&& cat /etc/jitsi/jibri/xorg-video-dummy.conf > /etc/jitsi/jibri/xorg-display1.conf \
+&& chown jibri /etc/jitsi/jibri/xorg-display[01].conf 
+
+# set default wallpaper
+cp /defaults/wallpaper.png /usr/share/icewm/themes/default/default.png
 
 # set default recording dir
 [ -z "${JIBRI_RECORDING_DIR}" ] \
